/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

/**
 *
 * @author Personal
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSTextFieldIconOne1 = new RSMaterialComponent.RSTextFieldIconOne();
        rSButtonShape1 = new RSMaterialComponent.RSButtonShape();

        setPreferredSize(new java.awt.Dimension(1290, 690));

        jPanel1.setBackground(new java.awt.Color(33, 34, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSTextFieldIconOne1.setBackground(new java.awt.Color(29, 30, 51));
        rSTextFieldIconOne1.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setText("Buscar...");
        rSTextFieldIconOne1.setAlignmentX(1.0F);
        rSTextFieldIconOne1.setBorderColor(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setColorIcon(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldIconOne1.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setPlaceholder("Buscar...");
        jPanel1.add(rSTextFieldIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 360, -1));

        rSButtonShape1.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonShape1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        rSButtonShape1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonShape1.setBorderPainted(false);
        rSButtonShape1.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        jPanel1.add(rSButtonShape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSButtonShape rSButtonShape1;
    private RSMaterialComponent.RSTextFieldIconOne rSTextFieldIconOne1;
    // End of variables declaration//GEN-END:variables
}
