/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Personal
 */
public class CrearUsuario extends javax.swing.JPanel {

    /**
     * Creates new form CrearCliente
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton1 = new rojeru_san.RSButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSComboBoxMaterial1 = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textField1 = new necesario.TextField();
        textField2 = new necesario.TextField();
        textField3 = new necesario.TextField();
        textField4 = new necesario.TextField();
        textField5 = new necesario.TextField();
        textField6 = new necesario.TextField();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(29, 30, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 30, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton2.setBackground(new java.awt.Color(67, 94, 190));
        rSButton2.setText("Guardar");
        rSButton2.setColorHover(new java.awt.Color(0, 153, 0));
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 110, -1));

        rSButton1.setBackground(new java.awt.Color(145, 152, 158));
        rSButton1.setText("Cancelar");
        rSButton1.setColorHover(new java.awt.Color(204, 0, 0));
        jPanel1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 110, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 70, 30));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, 30));

        rSComboBoxMaterial1.setBackground(new java.awt.Color(29, 30, 51));
        rSComboBoxMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        rSComboBoxMaterial1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ROL", "ADMINISTRADOR", "TRABAJADOR", "CONTADOR" }));
        rSComboBoxMaterial1.setColorMaterial(new java.awt.Color(255, 255, 255));
        jPanel1.add(rSComboBoxMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 380, 40));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 70, 30));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 30));

        textField1.setBackground(new java.awt.Color(29, 30, 51));
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setPlaceholder("Nombre");
        textField1.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 380, -1));

        textField2.setBackground(new java.awt.Color(29, 30, 51));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.setPlaceholder("Nombre");
        textField2.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 380, -1));

        textField3.setBackground(new java.awt.Color(29, 30, 51));
        textField3.setForeground(new java.awt.Color(255, 255, 255));
        textField3.setPlaceholder("Nombre");
        textField3.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 380, -1));

        textField4.setBackground(new java.awt.Color(29, 30, 51));
        textField4.setForeground(new java.awt.Color(255, 255, 255));
        textField4.setPlaceholder("Nombre");
        textField4.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField4.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 380, -1));

        textField5.setBackground(new java.awt.Color(29, 30, 51));
        textField5.setForeground(new java.awt.Color(255, 255, 255));
        textField5.setPlaceholder("Nombre");
        textField5.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField5.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 380, -1));

        textField6.setBackground(new java.awt.Color(29, 30, 51));
        textField6.setForeground(new java.awt.Color(255, 255, 255));
        textField6.setPlaceholder("Nombre");
        textField6.setSelectedTextColor(new java.awt.Color(29, 30, 51));
        textField6.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 380, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 880, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial1;
    private necesario.TextField textField1;
    private necesario.TextField textField2;
    private necesario.TextField textField3;
    private necesario.TextField textField4;
    private necesario.TextField textField5;
    private necesario.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
